name = "narcissus"
type = "javascript"
workers_dev = true
compatibility_date = "2021-08-27" # required
compatibility_flags = [ "formdata_parser_supports_files" ] # required

[vars]
WORKERS_RS_VERSION = "0.0.6"
# CORS_ORIGIN = "http://example.com:3030"
# SITE_URL = https://example.com

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir    = "build/worker"
format = "modules"
main   = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type  = "CompiledWasm"

# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
